# Generated by Django 3.2.9 on 2021-12-27 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YuksalishApp', '0004_events'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
    ]
