# Generated by Django 3.2.9 on 2021-12-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YuksalishApp', '0006_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viloyat', models.CharField(max_length=150, verbose_name='Viloyat')),
            ],
        ),
        migrations.RemoveField(
            model_name='events',
            name='viloyat',
        ),
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(upload_to='img', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='events',
            name='phone',
            field=models.CharField(max_length=13, verbose_name='Telefon raqam'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='F.I.O')),
                ('phone', models.CharField(max_length=13, verbose_name='Telefon Raqam')),
                ('image', models.ImageField(upload_to='img', verbose_name='Rasm')),
                ('manzil', models.ManyToManyField(to='YuksalishApp.Location')),
            ],
        ),
    ]
