# Generated by Django 3.2.9 on 2021-12-27 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YuksalishApp', '0007_auto_20211227_2129'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
    ]
