# Generated by Django 3.2.9 on 2021-12-27 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('YuksalishApp', '0009_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='manzil',
        ),
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='YuksalishApp.location'),
        ),
    ]
