# Generated by Django 3.2.9 on 2021-12-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YuksalishApp', '0012_alter_contact_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.ImageField(upload_to='img', verbose_name='Rasm'),
        ),
    ]
