# Generated by Django 3.2.9 on 2021-12-28 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YuksalishApp', '0015_alter_events_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='city',
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
