# Generated by Django 3.2.9 on 2021-12-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YuksalishApp', '0017_auto_20211228_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='null',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
