# Generated by Django 3.2.9 on 2021-12-28 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('YuksalishApp', '0019_alter_general_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='YuksalishApp.general'),
        ),
    ]
