# Generated by Django 3.2.9 on 2021-12-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YuksalishApp', '0020_alter_contact_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='city',
        ),
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.ManyToManyField(to='YuksalishApp.General'),
        ),
    ]
