# Generated by Django 3.2.9 on 2021-12-28 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YuksalishApp', '0021_auto_20211228_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='general',
            name='city',
        ),
    ]
