# Generated by Django 3.2.9 on 2021-12-28 12:43

import YuksalishApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YuksalishApp', '0022_remove_general_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='city',
            field=models.ManyToManyField(to='YuksalishApp.City'),
        ),
        migrations.AlterField(
            model_name='general',
            name='null',
            field=models.CharField(max_length=50, verbose_name=YuksalishApp.models.City),
        ),
    ]
