# Generated by Django 3.2.9 on 2021-12-29 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YuksalishApp', '0023_auto_20211228_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='general',
            name='city',
        ),
        migrations.RemoveField(
            model_name='general',
            name='viloyat',
        ),
        migrations.RemoveField(
            model_name='city',
            name='address',
        ),
        migrations.RemoveField(
            model_name='city',
            name='phone',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='General',
        ),
    ]
