# Generated by Django 3.2.9 on 2021-12-29 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('YuksalishApp', '0024_auto_20211229_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='F.I.O')),
                ('phone', models.CharField(max_length=13, verbose_name='Telefon Raqam')),
                ('image', models.ImageField(upload_to='img', verbose_name='Rasm')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='YuksalishApp.location')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YuksalishApp.city')),
            ],
        ),
    ]
