# Generated by Django 3.2.9 on 2021-12-30 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YuksalishApp', '0025_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
    ]
